### ISSUE TITLE
[Bug]: Call to filament-tour::open-tour doesn't work

### ISSUE THREAD

**Issue by ariko861** [JibayMcs/filament-tour#8] opened 2023-11-13 10:51 UTC
### What happened?

I can't make work the open-tour dispatch work.
From what I could gather, it seems to come from the js/index.js file on this line : 
`Livewire.on('filament-tour::open-tour', function (id) {
        let tour = tours.find(element => element.id === id);`
In livewire 3, dispatch send either an array or a dictionary, so tours.find will never find the right value here.
A simple work around to me would be to change it to let's say :
`Livewire.on('filament-tour::open-tour', function (event) {
        let tour = tours.find(element => element.id === event.id);`
But there may be other implications I haven't got through.

### How to reproduce the bug

Create a tour with Tour::make('tour_id') and try trigger it with `$this->dispatch('filament-tour::open-tour', 'tour_id');`

### Package Version

3.1.0.3

### PHP Version

8.2.0

### Laravel Version

10.31.0

**Comment by archilex** [comment] 2023-11-25 03:36
@ariko861 I just ran into this as well and the issue is that the plugin prefixes `tour_` to the `id`. So in your example instead of `tour_id` you'd need to call `tour_tour_id`. 

The docs need to be updated to reflect this.

**Comment by ariko861** [comment] 2023-12-11 14:04
Yes, I had noticed that and updated my code according to this already, but I believe the problem is deeper than that : 
when you dispatch an event from a livewire component with `$this->dispatch('filament-tour::open-tour', 'tour_id')`, it passes an array `[ 'id' => 'tour_id']`, but the function listening for the event is expecting to receive the id as a string.
That explains the change I describe in my first message.
It may be a collateral from upgrade from livewire 2 to 3.

**Comment by ghost** [comment] 2024-03-03 23:13
Unfortunately, I am unable to get this to work:

```
<button wire:click="$dispatch('filament-tour::open-tour', 'dashboard')">
    Show Dashboard tour
</button>
```

Any ideas?

**Comment by wallacemaxters** [comment] 2024-04-16 01:06
## Work around
To solve this, I had to do it like this:

```php

    protected function getHeaderActions(): array
    {
        return [
            Actions\Action::make('tour')->alpineClickHandler('Livewire.dispatch("filament-tour::open-tour", "tour_dashboard")'),
        ];
    }

    public function tours(): array
    {
         return [
            // 'dashboard' will generate 'tour_dashboard' id
            Tour::make('dashboard')
            ->steps(
                Step::make('.fi-avatar')
                    ->title('Woaw ! Here is your avatar !')
                    ->description('You look nice !')
                    ->icon('heroicon-o-user-circle')
                    ->iconColor('primary')
            ),
        ];
    }

```

Whenever you use the id you need to prefix it with "tour_" for it to work.


## Solution

In the `filament-tour/resources/js/index.js` the code should be change to:

```javascript
Livewire.on('filament-tour::open-tour', function (params) {

     let id;

      if (Array.isArray(params) {
           id = params[0];
      }
      else if (params?.id) {
         id = params.id;
     } else {
         id = params;
     }

      let tour = tours.find(element => element.id === id);

      if (tour) {
          openTour(tour);
      } else {
          console.error(`Tour with id '${id}' not found`);
      }
  });
```

**Comment by JibayMcs** [comment] 2024-08-06 12:15
Hi ! This bug will be fixed in the next update ! :)

**Comment by JibayMcs** [comment] 2024-08-06 12:30
Fixed here: https://github.com/JibayMcs/filament-tour/releases/tag/v3.1.0.6

**Closed as completed by JibayMcs** 2024-08-06 12:30 UTC
Labels: bug
